import Head from 'next/head'
import React from 'react'
import styles from '../../../styles/Home.module.scss'

export default function DefaultLayout({ children }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next.js transitions</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {children}
            </main>
        </div>
    )
}